### ISSUE TITLE
The WriteAsync method cannot be called when another write operation is pending.

### ISSUE THREAD

**Issue by zedle** [davidfowl/BedrockTransports#10]
Hello, 

We started dropping bedrock into our server application and have been getting this:

`[20:53:31 ERR] AuthWorker Error processing queue
System.AggregateException: One or more errors occurred. ( The WriteAsync method cannot be called when another write operation is pending.)
 ---> System.NotSupportedException:  The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory1 buffer)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ArchonPolicyServer.Server.Connections.BedrockConnection.SendAsync(Byte[] msg)`

Is there anything we may be doing wrong that may allow us to work around this issue?

We're using https://github.com/redhat-developer/kestrel-linux-transport along with it as the server runs on .NET Core 3 in linux.

Appreciate any insights you may have.

Thanks!

**Comment by davidfowl** [comment]
Can you show me what your application is doing?

**Comment by fuhry** [comment]
I can also confirm that swapping Red Hat's epoll based transport for good ole `.UseSockets()` produces the same behavior.

We are working on a minimal reproducer.

**Comment by davidfowl** [comment]
It seems like you're sending to the connection in an overlapping way (that isn't safe by default). Waiting on a repro 😄

**Comment by fuhry** [comment]
We suspect it's within SslStream. We tried doing `.WriteAsync().Wait()` with a lock around it just to see if it was something in our own code, and observed no change in behavior (besides everything slowing greatly of course). The test client I'm using to produce this behavior also works in a half-duplex fashion, never sending a message before receiving a response to the previous message, and our server is sending msgpack structures all in a single write call. Theoretically this should mean that even unsafe code on the server should never trigger an unsafe write, but here we are.

I'll find some time today or tomorrow to get a minimal reproducer working.

**Comment by fuhry** [comment]
@davidfowl Here you go:

https://github.com/fuhry/BedrockSSLWriteRepro

**Comment by davidfowl** [comment]
If you set WORKER_COUNT 
 to 1 (Workerhttps://github.com/fuhry/BedrockSSLWriteRepro/blob/master/EchoServerApplication.cs#L80) does it repro?

**Comment by fuhry** [comment]
With 1 worker it doesn't reproduce.

It is still reproducible if I add `await connection.Transport.Output.FlushAsync();` at the end of HandleMessage.

It is not reproducible if you take TLS out of the equation. I updated my reproducer to run both TLS and non-TLS versions of the server side by side. Clients are now renamed to `tls_client.py` and `plain_client.py`. This is what leads me to believe the real issue is in SslStream.

**Comment by fuhry** [comment]
Also, I added a crude exponential backoff to HandleMessage. With this approach, writes do eventually succeed but this is obviously a pretty hacky workaround that can get out of control quickly with the volume we're expecting for this server application.

**Comment by davidfowl** [comment]
I'm not 100% convinced as yet. Looking at the code I don't know how you avoid multiple overlapping writes to the same `ConnectionContext`.

**Comment by fuhry** [comment]
With this version the issue reproduces much less frequently but still happens:

```c#
private async Task HandleMessage(ConnectionContext connection, byte[] msg)
{
    try
    {
        lock (connection.Transport.Output)
        {
            connection.Transport.Output.WriteAsync(msg).AsTask().Wait();
        }
    }
    catch (NotSupportedException e)
    {
        _logger.LogError(e, "NotSupportedException");
    }
    await connection.Transport.Output.FlushAsync();
}
```

**Comment by davidfowl** [comment]
Add a semaphore and use WaitAsync, Release instead of locking and using .Wait. See if that solves the problem e.g. https://github.com/davidfowl/BedrockTransports/blob/1c7dd50778173cca62a007388d1730ab5afb73bd/Bedrock.Framework/Protocols/Protocol.cs#L43-L53

**Comment by fuhry** [comment]
So with a semaphore this is working. Thanks - it looks like `Bedrock.Framework.Protocols.Protocol` is a higher level wrapper than the `PipeReader` and `PipeWriter` passed in through the connection context? Will `B.F.P.Protocol` be the recommended implementation for readers and writers in the future, or is it too early to tell?

**Comment by davidfowl** [comment]
@fuhry That's the direction I'd like to go with it. Create an ecosystem of reader and writers that can be used to compose higher level protocols or build your own parsers.
