### ISSUE TITLE
Potential torn read/write

### ISSUE THREAD

**Issue by omariom** [davidfowl/BedrockTransports#2]
I believe a  torn read/write may happen here:
https://github.com/davidfowl/BedrockTransports/blob/e02b10a83d18bdd79e18f8bbc52f40cc17a707bb/Bedrock.Framework/Server/ServerApplication.cs#L48

and here:
https://github.com/davidfowl/BedrockTransports/blob/e02b10a83d18bdd79e18f8bbc52f40cc17a707bb/Bedrock.Framework/Server/ServerApplication.cs#L73

**Comment by davidfowl** [comment]
Should be fixed. Thanks!

**Comment by omariom** [comment]
@davidfowl 

Another question is calling IConnectionListener methods from multiple threads.
Is it thread safe?

**Comment by davidfowl** [comment]
Yes
