### ISSUE TITLE
Socket.SendAsync cpu usage

### ISSUE THREAD

**Issue by JanEggers** [davidfowl/BedrockTransports#7]
when running my benchmark a large chunk of the cpu is in Socket.SendAsync is this expected?

Im not sure if the vs profiler is accurate.

![image](https://user-images.githubusercontent.com/6747376/67414132-c3dcd180-f5c2-11e9-9452-a51f6a4bbe9b.png)

**Comment by davidfowl** [comment]
Looks right, that's usually where most of the time is spent.

**Comment by JanEggers** [comment]
I was under the impression that SendAsync  should use async IO internally and therefore not use that much cpu.  but if you say its ok ill close this one.

**Comment by davidfowl** [comment]
> I was under the impression that SendAsync should use async IO internally and therefore not use that much cpu. but if you say its ok ill close this one.

SendAsync only goes async if you hit backpressure calling the OS API. If it completes synchronously it's because there's no back pressure from the other side its a simple copy into the kernel buffer
